### ISSUE TITLE
Bring type context to the let-variables of directives

### ISSUE THREAD

**Issue by Lonli-Lokli** [wmaurer/ngx-fp-ts#4]
Starting with Ivy it's possible to introduce typed context to the let-variables, see  ngTemplateContextGuard
https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_if.ts

It will be great as let-v variable is of type any now.

**Comment by wmaurer** [comment]
Thanks for the suggestion. I've looked into this in the past and was unable to get it working, but I'll try again.

**Comment by Lonli-Lokli** [comment]
@wmaurer I can prepare PR for this, I was able to do it for Right case, as Ivy does not allow this for Left.

**Comment by Lonli-Lokli** [comment]
@wmaurer Could you please review PR?
